[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_programs = "46Brqof8bysRqDbaYH1NTdYWfYP53zb1JfXPPX5nC1xL"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
